---
title: "R Notebook"
output: html_notebook
---

Manage packages.
```{r}
pacman::p_load(tidyverse,
               coin)
```

Get data.
```{r}
train_weather <- read_csv("data/train_aggregated_weather_1_853.csv") %>% select(-1,-2) %>%
  mutate(annee=str_sub(date_target,1,4),
         geoid = ifelse(nchar(geoid)<5,paste0("0",geoid),geoid))

data_train <- read_csv("data/semaine_train.csv") 
  
magic <- left_join(data_train,train_weather %>% select(-week,-annee),
                   by = c("county"="geoid",
                          "date_semaine"="date_target"))

rm(data_train, train_weather)
```

Create a random subsample for play, retaining only complete cases.
```{r}
ssize <- 2000
sub_train <- sample_n(magic, ssize)
sub_train <- sub_train[complete.cases(sub_train),]

colnames(sub_train)
```
Set up functions and space for simple two-group comparisons.
```{r}
ttest_pvalue <- function(x,y) {
    k <- t.test(x,y)
    as.numeric(k[3])}

wilcox_pvalue <- function(x,y) {
    k <- wilcox.test(x,y)
    as.numeric(k[3])}

permute_pvalue <- function(x,y) {
    grp_1 <- rep(1, length(x))
    grp_2 <- rep(2, length(y))
    val_1 <- data.frame(x, grp_1)
    colnames(val_1) <- c("XXX", "group")
    val_2 <- data.frame(y, grp_2)
    colnames(val_2) <- c("XXX", "group")
    dataa <- rbind(val_1, val_2)
    k <- independence_test(formula = XXX~group, data = dataa)
    pvalue(k)}

tt <- c(); wcmw <- c(); perm <- c()

```

Set up populations to be compared.
```{r}
quant_vars <- c("X11_Open_water",
                "X21_Developed_open_space",
                "X22_Developed_low_intensity",
                "X23_Developed_medium_intensity",
                "X24_Developed_high_intensity",
                "X31_Barren_land_rock_sand_clay",
                "X41_Deciduous_forest",
                "X42_Evergreen_forest",
                "X43_Mixed_forest",
                "X52_Shrub_scrub",
                "X71_Grassland_herbaceous",
                "X81_Pasture_hay",
                "X82_Cultivated_crops",
                "X90_Woody_wetlands",
                "X95_Emergent_herbaceous_wetlands",
                "X0_0",
                "X12_Perennial_ice_snow",
                "pop_year",
                "nb_feux_voisins",
                "nb_feux_voisins_lag",
                "av_temp_hi",
                "av_temp_lo",
                "av_temp_mean",
                "av_precip",
                "av_wind_speed",
                "av_cloud_cover",
                "av_humidity" )

c1q <- sub_train[sub_train$FIRE, quant_vars]
c2q <- sub_train[!sub_train$FIRE, quant_vars]



```

Compare two populations
```{r}

sapply(c1q, as.numeric)
sapply(c2q, as.numeric)

for (j in 1:dim(c1q)[2]){
    tt[j] <- ttest_pvalue(c1q[,j], c2q[,j])
    #wcmw[j] <- wilcox_pvalue(c1q[,j], c2q[,j])
    perm[j] <- permute_pvalue(c1q[,j], c2q[,j])
}

options(scipen = 999)

two_group_comparisons <- data.frame(quant_vars, tt,  perm)
colnames(two_group_comparisons) <- c("variable", "t-test",  "permutation")

```

```{r}
write.csv(two_group_comparisons, "USA_two_group_comparisons.csv")
write.csv2(two_group_comparisons, "FRANCE_two_group_comparisons.csv")
```













